### PR TITLE
Fixed a bug which was resulting in a larger and incorrect hit ratio.

### PR DESCRIPTION
**Pull request by bigdata2**
Fixed a bug in shadowlru.cpp

### CODE REVIEW

**Comment by rstutsman** [comment]
@bigdata2 Can you explain a bit more? My co-author and I reviewed the change, but it looks incorrect to us. The shadow distance (in bytes) is the sum of all items in the LRU chain that precede the hit item, regardless of their key.

**Comment by bigdata2** [comment]
@rstutsman First, let me summarize what I am trying to do. I am trying to compare cache policy for memcached, which according to readme file is ShadowSlab with memshare. 

I took the following test-case from the test directory and ran lsm-sim using shadoslab policy:
../../lsm-sim -a 1 -w 0 -p shadowslab -f ./tmp
tmp file is:
1.5,1,1,5,10,100,1
1.55,1,1,4,10,100,1
1.6,1,1,6,10,100,1
1.65,1,1,4,10,101,1
1.7,1,1,7,10,102,1
1.75,1,1,4,10,101,1

The result of this run is as follows;
 app policy global_mem segment_size block_size num_sections num_dsections cleaning_width growt
h_factor hits accesses hit_rate bytes_cached missed_bytes evicted_bytes evicted_items cleaned
_generated_segs cleaned_ext_frag_bytes hits_dram hits_flash writes_flash credit_limit flash_b
ytes_written dram_size flash_size threshold 
1 shadowslab 51209600 0 0 0 0 0 1.25 5 6 0.833333 0 0 0 0 0 0 0 0 0 0 0 0 0 0 

It reports 5 hits out of 6 accesses. I expected  3 hits out 6 accesses as reported by another run using lsm policy. 
However, in the current code it will never happen because [this](https://github.com/utah-scs/lsm-sim/blob/master/src/shadowlru.cpp#L64) condition will not be true for the items after the first line in the test-case. Perhaps it is the desired implementation, but it does not appear correct to me for the aforementioned test-case when memcached is used, which is empty at the beginning of time. 
Can you explain why there should be 5 hits instead of 3 when an empty memcached is used? 

Another unrelated issue -- is there a tool to generate synthetic trace file using let's say a normal distribution to compare various policies? If not, can you explain how trace file was generated to compare memshare with other policies or can you share a trace file?

**Comment by rstutsman** [comment]
We don't have a tool to synthesize traces. We were hoping to collect a public redis trace from another researcher, but so far we haven't heard back from his group. It's likely we could generate something, though; perhaps we could even use distributions drawn from the sensitive trace we have.

Any policy that starts with "shadow" is a bit weird. It may or may not correctly track hits/misses. I'll take a look to try to answer your question in more detail. But, the main point is the "shadow" policies don't work like a normal cache. The only valid information they dump is the hit rate curve at the end of the simulation. This is something like simulating all possible cache sizes at once and showing for all the sizes what the hit rate would be. Part of how this is structured is a historical accident.

For Memshare, the paper doesn't use the "shadow" policies. The policies you want to try are lru (pure lru), slab (memcached/Memcachier like; slab sizes are configurable on command line), and lsc_multi (Memshare i.e. "multitenant log structured cache").

I pinged my coauthor re the traces. I'll give him a call tomorrow and try to come up with a reasonable solution; we can probably write a synthetic trace generator to unblock you.

**Comment by danielrushton** [comment]
Just briefly chiming in here, I don’t believe the policy for memcached should be shadow-anything. If the README states so it is incorrect and I will fix it. Memcached is strictly a vanilla slab-based implementation, I don’t recall how we modeled that exactly. Shadow-queues are something we introduced and DNE in memcached.

**Pull request closed without merging**
